-- Yasui / takai pilot: route inflected searches to a lexical family, split examples by sense,
-- and connect opposites at sense level. The migration is idempotent so it can be replayed.

select pg_advisory_xact_lock(hashtext('kimtokki_yasui_takai_sense_pilot_v1'));

create table if not exists public.sense_search_form (
  id bigint generated by default as identity primary key,
  search_text text not null,
  search_norm text not null,
  expression_family_id bigint not null references public.expression_family(id) on delete cascade,
  sense_id bigint references public.sense(id) on delete cascade,
  match_scope text not null check (match_scope in ('FAMILY','SENSE')),
  form_type text not null check (form_type in ('PRONUNCIATION','MEANING','INFLECTION','PATTERN')),
  priority integer not null default 100,
  source_type text not null default 'SYSTEM_RULE' check (source_type in ('SYSTEM_RULE','USER_CONFIRMED','RAW_NOTE')),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','HOLD','EXCLUDED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((match_scope='FAMILY' and sense_id is null) or (match_scope='SENSE' and sense_id is not null))
);

create unique index if not exists ux_sense_search_form_route
  on public.sense_search_form (search_norm, expression_family_id, coalesce(sense_id,0), form_type);
create index if not exists ix_sense_search_form_search_norm_active
  on public.sense_search_form (search_norm, priority desc) where status='ACTIVE';
create index if not exists ix_sense_search_form_family on public.sense_search_form (expression_family_id);
create index if not exists ix_sense_search_form_sense on public.sense_search_form (sense_id) where sense_id is not null;

create index if not exists ix_sense_relation_from_active
  on public.sense_relation (from_sense_id,display_order) where status='ACTIVE';
create index if not exists ix_sense_relation_to_active
  on public.sense_relation (to_sense_id,display_order) where status='ACTIVE' and is_bidirectional;

insert into public.expression_family (family_key,working_label,status,verification_status,created_at,updated_at)
values
  ('F_YASUI_LEXICAL','야스이','ACTIVE','VERIFIED',now(),now()),
  ('F_YASUI_SUFFIX','~야스이','ACTIVE','VERIFIED',now(),now()),
  ('F_TAYASUI','타야스이','ACTIVE','VERIFIED',now(),now()),
  ('F_TAKAI_LEXICAL','타카이','ACTIVE','VERIFIED',now(),now())
on conflict (family_key) do update
set working_label=excluded.working_label,status='ACTIVE',verification_status='VERIFIED',updated_at=now();

insert into public.sense
  (sense_key,expression_family_id,meaning_text,meaning_norm,sense_order,is_primary,usage_summary,status,verification_status,created_at,updated_at)
select v.sense_key,f.id,v.meaning_text,lower(btrim(v.meaning_text)),v.sense_order,v.is_primary,v.usage_summary,
       'ACTIVE','VERIFIED',now(),now()
from (values
  ('S_YASUI_PRICE','F_YASUI_LEXICAL','싸다',1,true,'가격·비용이 낮다'),
  ('S_YASUI_EASY','F_YASUI_LEXICAL','쉽다',2,false,'독립 형용사 야스이의 용이성 의미'),
  ('S_YASUI_SUFFIX_EASY','F_YASUI_SUFFIX','~하기 쉽다·편하다',1,true,'동사 어간에 붙는 ~야스이'),
  ('S_TAYASUI_EASY','F_TAYASUI','손쉽다·용이하다',1,true,'독립 표현 타야스이'),
  ('S_TAKAI_PRICE','F_TAKAI_LEXICAL','비싸다',1,true,'가격·비용이 높다'),
  ('S_TAKAI_HEIGHT','F_TAKAI_LEXICAL','높다·키가 크다',2,false,'장소의 높이 또는 사람의 신장'),
  ('S_TAKAI_DEGREE','F_TAKAI_LEXICAL','정도·기준 등이 크다·높다',3,false,'습도·이상·텐션 등 추상적 정도')
) v(sense_key,family_key,meaning_text,sense_order,is_primary,usage_summary)
join public.expression_family f on f.family_key=v.family_key
on conflict (sense_key) do update
set expression_family_id=excluded.expression_family_id,meaning_text=excluded.meaning_text,
    meaning_norm=excluded.meaning_norm,sense_order=excluded.sense_order,is_primary=excluded.is_primary,
    usage_summary=excluded.usage_summary,status='ACTIVE',verification_status='VERIFIED',updated_at=now();

insert into public.expression_family_member
  (expression_family_id,expression_id,member_role,display_order,status,created_at)
select f.id,v.expression_id,'BASE',1,'ACTIVE',now()
from (values ('F_YASUI_LEXICAL',7030::bigint),('F_TAKAI_LEXICAL',7049::bigint)) v(family_key,expression_id)
join public.expression_family f on f.family_key=v.family_key
join public.expression e on e.id=v.expression_id and e.status='ACTIVE'
where not exists (
  select 1 from public.expression_family_member m
  where m.expression_family_id=f.id and m.expression_id=v.expression_id
);

create temporary table _pilot_expression_sense (
  expression_id bigint not null,
  sense_key text not null,
  applicability text not null default 'DIRECT'
) on commit drop;

insert into _pilot_expression_sense (expression_id,sense_key,applicability) values
  (789,'S_YASUI_PRICE','DIRECT'),(1582,'S_YASUI_PRICE','DIRECT'),(1583,'S_YASUI_PRICE','DIRECT'),
  (1584,'S_YASUI_PRICE','DIRECT'),(2383,'S_YASUI_PRICE','DIRECT'),(2876,'S_YASUI_PRICE','DIRECT'),
  (3865,'S_YASUI_PRICE','DIRECT'),(3866,'S_YASUI_PRICE','DIRECT'),(5040,'S_YASUI_PRICE','DIRECT'),
  (6137,'S_YASUI_PRICE','DIRECT'),(6244,'S_YASUI_PRICE','DIRECT'),(6245,'S_YASUI_PRICE','DIRECT'),
  (7030,'S_YASUI_EASY','DIRECT'),
  (1579,'S_YASUI_SUFFIX_EASY','DIRECT'),(1581,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1585,'S_YASUI_SUFFIX_EASY','DIRECT'),(1586,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1587,'S_YASUI_SUFFIX_EASY','DIRECT'),(1588,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1589,'S_YASUI_SUFFIX_EASY','DIRECT'),(1590,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1591,'S_YASUI_SUFFIX_EASY','DIRECT'),(1592,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1593,'S_YASUI_SUFFIX_EASY','DIRECT'),(1594,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (1595,'S_YASUI_SUFFIX_EASY','DIRECT'),(1596,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (3072,'S_YASUI_SUFFIX_EASY','DIRECT'),(3224,'S_YASUI_SUFFIX_EASY','DIRECT'),
  (6376,'S_YASUI_SUFFIX_EASY','DIRECT'),(1580,'S_TAYASUI_EASY','DIRECT'),
  (836,'S_TAKAI_PRICE','DIRECT'),(3292,'S_TAKAI_PRICE','DIRECT'),
  (3863,'S_TAKAI_PRICE','DIRECT'),(5037,'S_TAKAI_PRICE','DIRECT'),
  (5227,'S_TAKAI_PRICE','DIRECT'),(6243,'S_TAKAI_PRICE','DIRECT'),(7219,'S_TAKAI_PRICE','DIRECT'),
  (4684,'S_TAKAI_DEGREE','DIRECT'),(6159,'S_TAKAI_DEGREE','DIRECT'),(6857,'S_TAKAI_DEGREE','DIRECT');

insert into public.expression_sense (expression_id,sense_id,applicability,status,created_at)
select p.expression_id,s.id,p.applicability,'ACTIVE',now()
from _pilot_expression_sense p
join public.expression e on e.id=p.expression_id and e.status='ACTIVE'
join public.sense s on s.sense_key=p.sense_key
on conflict (expression_id,sense_id) do update set applicability=excluded.applicability,status='ACTIVE';

-- Three HIGH-confidence raw-note examples fill the otherwise empty height sense.
create temporary table _pilot_raw_example on commit drop as
select * from jsonb_to_recordset($json$[
 {"legacy_key":"SENSE-PILOT-TAKAI-HEIGHT-01","memo_seq":1358655,"meaning":"높은 곳은 싫어요","pronunciation":"타카이 토코로와 키라이데스","jp":"高い所は嫌いです","excerpt":"높은곳은 싫어요, 타카이 토코로와 키라이데스"},
 {"legacy_key":"SENSE-PILOT-TAKAI-HEIGHT-02","memo_seq":1828842,"meaning":"키가 크다","pronunciation":"세가 다카이","jp":"背が高い","excerpt":"키가 크다 -세가 다카이"},
 {"legacy_key":"SENSE-PILOT-TAKAI-HEIGHT-03","memo_seq":2398502,"meaning":"높은 곳으로 도망쳐","pronunciation":"타카이 토코로니 니게테","jp":"高い所に逃げて","excerpt":"타카이 토코로니 니게테! -높은 곳으로 도망가!"}
]$json$::jsonb) as x(legacy_key text,memo_seq bigint,meaning text,pronunciation text,jp text,excerpt text);

insert into public.candidate_unit
  (source_memo_id,legacy_candidate_key,korean_meaning,display_pronunciation,japanese_original,
   personal_note,literal_translation,recovery_method,verification_status,source_record_ref,
   source_excerpt,source_folder_snapshot,source_file_snapshot,created_at)
select sm.id,x.legacy_key,x.meaning,x.pronunciation,x.jp,'타카이의 높이·신장 의미 시험 예문',null,
       'RAW_NOTE_SENSE_PILOT','VERIFIED','sense-pilot:yasui-takai:v1',x.excerpt,
       '김토끼니혼고/원본메모','야스이·타카이 1차 의미 분기',now()
from _pilot_raw_example x join public.source_memo sm on sm.memo_seq=x.memo_seq
where not exists (select 1 from public.candidate_unit cu where cu.legacy_candidate_key=x.legacy_key);

insert into public.expression
  (display_pronunciation,japanese_original,status,verification_status,speaking_enabled,listening_enabled,edge_flag,created_at,updated_at)
select x.pronunciation,x.jp,'ACTIVE','VERIFIED',true,true,false,now(),now()
from _pilot_raw_example x
where not exists (
  select 1 from public.expression e
  where regexp_replace(lower(coalesce(e.display_pronunciation,'')),'[^0-9a-z가-힣ぁ-んァ-ヶ一-龠]','','g')=
        regexp_replace(lower(x.pronunciation),'[^0-9a-z가-힣ぁ-んァ-ヶ一-龠]','','g')
    and e.status<>'EXCLUDED'
);

create temporary table _pilot_raw_resolved on commit drop as
select distinct on (x.legacy_key) x.*,sm.id source_memo_id,cu.id candidate_unit_id,e.id expression_id
from _pilot_raw_example x
join public.source_memo sm on sm.memo_seq=x.memo_seq
join public.candidate_unit cu on cu.legacy_candidate_key=x.legacy_key
join public.expression e
  on regexp_replace(lower(coalesce(e.display_pronunciation,'')),'[^0-9a-z가-힣ぁ-んァ-ヶ一-龠]','','g')=
     regexp_replace(lower(x.pronunciation),'[^0-9a-z가-힣ぁ-んァ-ヶ一-龠]','','g')
 and e.status='ACTIVE'
order by x.legacy_key,e.id;

insert into public.expression_meaning
  (expression_id,meaning_text,meaning_norm,meaning_order,is_primary,usage_note,created_at)
select r.expression_id,r.meaning,lower(btrim(r.meaning)),1,true,'타카이의 높이·신장 의미',now()
from _pilot_raw_resolved r
where not exists (select 1 from public.expression_meaning em where em.expression_id=r.expression_id and em.is_primary);

insert into public.search_alias (expression_id,alias_text,alias_norm,alias_type,origin,created_at)
select r.expression_id,r.pronunciation,lower(btrim(r.pronunciation)),'NORMALIZED','SOURCE',now()
from _pilot_raw_resolved r
where not exists (
  select 1 from public.search_alias sa
  where sa.expression_id=r.expression_id and sa.alias_type='NORMALIZED' and sa.alias_norm=lower(btrim(r.pronunciation))
);

insert into public.expression_source (expression_id,candidate_unit_id,created_at)
select r.expression_id,r.candidate_unit_id,now() from _pilot_raw_resolved r
where not exists (select 1 from public.expression_source es where es.candidate_unit_id=r.candidate_unit_id);

insert into public.expression_sense (expression_id,sense_id,applicability,status,created_at)
select r.expression_id,s.id,'DIRECT','ACTIVE',now()
from _pilot_raw_resolved r join public.sense s on s.sense_key='S_TAKAI_HEIGHT'
on conflict (expression_id,sense_id) do update set applicability='DIRECT',status='ACTIVE';

-- Remove only the three verified cross-sense FORM edges. Their rows linked the easy headword
-- directly to price inflections and caused the two meanings to be mixed.
delete from public.expression_relation
where (id,from_expression_id,to_expression_id) in (
  (1037,7030,1584),(1038,7030,1582),(1044,7030,1583)
);

create temporary table _pilot_route (
  search_text text, family_key text, sense_key text, match_scope text, form_type text, priority integer, source_type text
) on commit drop;

insert into _pilot_route values
  ('야스이','F_YASUI_LEXICAL',null,'FAMILY','PRONUNCIATION',120,'USER_CONFIRMED'),
  ('야스쿠','F_YASUI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('야스캇타','F_YASUI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('야스이데스','F_YASUI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('싸다','F_YASUI_LEXICAL','S_YASUI_PRICE','SENSE','MEANING',120,'USER_CONFIRMED'),
  ('싸게','F_YASUI_LEXICAL','S_YASUI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('쌉니다','F_YASUI_LEXICAL','S_YASUI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('쌌다','F_YASUI_LEXICAL','S_YASUI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('쉽다','F_YASUI_LEXICAL','S_YASUI_EASY','SENSE','MEANING',120,'USER_CONFIRMED'),
  ('쉽게','F_YASUI_LEXICAL','S_YASUI_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('쉬웠다','F_YASUI_LEXICAL','S_YASUI_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('~야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','PATTERN',120,'USER_CONFIRMED'),
  ('타베야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('타베야스쿠','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('타베야스캇타','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('이키야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('이키야스쿠','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('이키야스캇타','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('노미야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('노미야스쿠','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('노미야스캇타','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('하나시야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('키키야스이','F_YASUI_SUFFIX','S_YASUI_SUFFIX_EASY','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('타야스이','F_TAYASUI','S_TAYASUI_EASY','SENSE','PRONUNCIATION',120,'USER_CONFIRMED'),
  ('타카이','F_TAKAI_LEXICAL',null,'FAMILY','PRONUNCIATION',120,'USER_CONFIRMED'),
  ('다카이','F_TAKAI_LEXICAL',null,'FAMILY','PRONUNCIATION',120,'SYSTEM_RULE'),
  ('다까이','F_TAKAI_LEXICAL',null,'FAMILY','PRONUNCIATION',110,'SYSTEM_RULE'),
  ('타카쿠','F_TAKAI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('다카쿠','F_TAKAI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('타카캇타','F_TAKAI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('다카캇타','F_TAKAI_LEXICAL',null,'FAMILY','INFLECTION',115,'SYSTEM_RULE'),
  ('비싸다','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','MEANING',120,'USER_CONFIRMED'),
  ('비싸게','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('비쌉니다','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('비쌌다','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('높다','F_TAKAI_LEXICAL','S_TAKAI_HEIGHT','SENSE','MEANING',120,'USER_CONFIRMED'),
  ('높다','F_TAKAI_LEXICAL','S_TAKAI_DEGREE','SENSE','MEANING',115,'USER_CONFIRMED'),
  ('높게','F_TAKAI_LEXICAL','S_TAKAI_HEIGHT','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('높게','F_TAKAI_LEXICAL','S_TAKAI_DEGREE','SENSE','INFLECTION',110,'SYSTEM_RULE'),
  ('높았다','F_TAKAI_LEXICAL','S_TAKAI_HEIGHT','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('높았다','F_TAKAI_LEXICAL','S_TAKAI_DEGREE','SENSE','INFLECTION',110,'SYSTEM_RULE'),
  ('크다','F_TAKAI_LEXICAL','S_TAKAI_HEIGHT','SENSE','MEANING',110,'SYSTEM_RULE'),
  ('크다','F_TAKAI_LEXICAL','S_TAKAI_DEGREE','SENSE','MEANING',105,'SYSTEM_RULE'),
  ('타카스기','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE'),
  ('다카스기','F_TAKAI_LEXICAL','S_TAKAI_PRICE','SENSE','INFLECTION',115,'SYSTEM_RULE');

insert into public.sense_search_form
  (search_text,search_norm,expression_family_id,sense_id,match_scope,form_type,priority,source_type,status,created_at,updated_at)
select r.search_text,regexp_replace(lower(btrim(r.search_text)),'[[:space:][:punct:]]','','g'),f.id,s.id,
       r.match_scope,r.form_type,r.priority,r.source_type,'ACTIVE',now(),now()
from _pilot_route r
join public.expression_family f on f.family_key=r.family_key
left join public.sense s on s.sense_key=r.sense_key
on conflict (search_norm,expression_family_id,(coalesce(sense_id,0)),form_type) do update
set search_text=excluded.search_text,match_scope=excluded.match_scope,priority=excluded.priority,
    source_type=excluded.source_type,status='ACTIVE',updated_at=now();

insert into public.sense_relation
  (from_sense_id,to_sense_id,relation_type,relation_subtype,is_bidirectional,display_order,status,verification_status,created_at,updated_at)
select least(a.id,b.id),greatest(a.id,b.id),v.relation_type,v.relation_subtype,true,v.display_order,'ACTIVE','VERIFIED',now(),now()
from (values
  ('S_YASUI_PRICE','S_TAKAI_PRICE','ANTONYM','PRICE',1),
  ('S_YASUI_EASY','S_YASUI_SUFFIX_EASY','RELATED','EASY_EXPRESSION',2),
  ('S_YASUI_EASY','S_TAYASUI_EASY','RELATED','EASY_EXPRESSION',3)
) v(from_key,to_key,relation_type,relation_subtype,display_order)
join public.sense a on a.sense_key=v.from_key
join public.sense b on b.sense_key=v.to_key
where not exists (
  select 1 from public.sense_relation sr
  where sr.from_sense_id=least(a.id,b.id) and sr.to_sense_id=greatest(a.id,b.id)
    and sr.relation_type=v.relation_type and coalesce(sr.relation_subtype,'')=coalesce(v.relation_subtype,'')
);

update public.sense_relation sr
set is_bidirectional=true,display_order=v.display_order,status='ACTIVE',verification_status='VERIFIED',updated_at=now()
from (values
  ('S_YASUI_PRICE','S_TAKAI_PRICE','ANTONYM','PRICE',1),
  ('S_YASUI_EASY','S_YASUI_SUFFIX_EASY','RELATED','EASY_EXPRESSION',2),
  ('S_YASUI_EASY','S_TAYASUI_EASY','RELATED','EASY_EXPRESSION',3)
) v(from_key,to_key,relation_type,relation_subtype,display_order)
join public.sense a on a.sense_key=v.from_key
join public.sense b on b.sense_key=v.to_key
where sr.from_sense_id=least(a.id,b.id) and sr.to_sense_id=greatest(a.id,b.id)
  and sr.relation_type=v.relation_type and coalesce(sr.relation_subtype,'')=coalesce(v.relation_subtype,'');

alter table public.expression_family enable row level security;
alter table public.expression_family_member enable row level security;
alter table public.sense enable row level security;
alter table public.expression_sense enable row level security;
alter table public.sense_search_form enable row level security;
alter table public.sense_relation enable row level security;

drop policy if exists app_read_active_expression_family on public.expression_family;
create policy app_read_active_expression_family on public.expression_family for select to anon,authenticated
using (status='ACTIVE');
drop policy if exists app_read_active_expression_family_member on public.expression_family_member;
create policy app_read_active_expression_family_member on public.expression_family_member for select to anon,authenticated
using (status='ACTIVE' and expression_family_id in (select id from public.expression_family where status='ACTIVE'));
drop policy if exists app_read_active_sense on public.sense;
create policy app_read_active_sense on public.sense for select to anon,authenticated
using (status='ACTIVE' and expression_family_id in (select id from public.expression_family where status='ACTIVE'));
drop policy if exists app_read_active_expression_sense on public.expression_sense;
create policy app_read_active_expression_sense on public.expression_sense for select to anon,authenticated
using (status='ACTIVE' and expression_id in (select id from public.expression where status='ACTIVE')
       and sense_id in (select id from public.sense where status='ACTIVE'));
drop policy if exists app_read_active_sense_search_form on public.sense_search_form;
create policy app_read_active_sense_search_form on public.sense_search_form for select to anon,authenticated
using (status='ACTIVE' and expression_family_id in (select id from public.expression_family where status='ACTIVE')
       and (sense_id is null or sense_id in (select id from public.sense where status='ACTIVE')));
drop policy if exists app_read_active_sense_relation on public.sense_relation;
create policy app_read_active_sense_relation on public.sense_relation for select to anon,authenticated
using (status='ACTIVE' and from_sense_id in (select id from public.sense where status='ACTIVE')
       and to_sense_id in (select id from public.sense where status='ACTIVE'));

grant select on public.expression,public.expression_meaning,
  public.expression_family,public.expression_family_member,public.sense,public.expression_sense,
  public.sense_search_form,public.sense_relation to anon,authenticated;

create or replace function public.search_expression_sense_hub(p_query text,p_limit integer default 12)
returns table(
  family_id bigint,family_key text,display_pronunciation text,
  sense_id bigint,sense_key text,meaning_text text,usage_summary text,
  sense_order integer,match_type text,score real,examples jsonb,relations jsonb
)
language sql stable security invoker set search_path=''
as $function$
with q as (
  select regexp_replace(lower(btrim(coalesce(p_query,''))),'[[:space:][:punct:]]','','g') norm
), routes as (
  select sf.*,row_number() over (order by sf.priority desc,sf.id) route_order
  from public.sense_search_form sf,q
  where sf.status='ACTIVE' and sf.search_norm=q.norm and q.norm<>''
), targets as (
  select distinct on (s.id)
    f.id family_id,f.family_key,f.working_label display_pronunciation,
    s.id sense_id,s.sense_key,s.meaning_text,s.usage_summary,s.sense_order,
    r.form_type match_type,r.priority,r.route_order
  from routes r
  join public.expression_family f on f.id=r.expression_family_id and f.status='ACTIVE'
  join public.sense s on s.expression_family_id=f.id and s.status='ACTIVE'
   and (r.sense_id is null or s.id=r.sense_id)
  order by s.id,r.priority desc,r.route_order
), limited as (
  select * from targets order by priority desc,family_id,sense_order limit greatest(1,least(coalesce(p_limit,12),50))
)
select l.family_id,l.family_key,l.display_pronunciation,l.sense_id,l.sense_key,l.meaning_text,l.usage_summary,
       l.sense_order,l.match_type,(l.priority::real/100.0)::real score,
       coalesce(ex.examples,'[]'::jsonb),coalesce(rel.relations,'[]'::jsonb)
from limited l
left join lateral (
  select jsonb_agg(jsonb_build_object(
    'expression_id',x.expression_id,'meaning_text',x.meaning_text,
    'display_pronunciation',x.display_pronunciation,'japanese_original',x.japanese_original,
    'applicability',x.applicability
  ) order by x.expression_id) examples
  from (
    select es.expression_id,e.display_pronunciation,e.japanese_original,es.applicability,em.meaning_text
    from public.expression_sense es
    join public.expression e on e.id=es.expression_id and e.status='ACTIVE'
    join lateral (
      select m.meaning_text from public.expression_meaning m
      where m.expression_id=e.id order by m.is_primary desc,m.meaning_order,m.id limit 1
    ) em on true
    where es.sense_id=l.sense_id and es.status='ACTIVE'
    order by es.expression_id limit 30
  ) x
) ex on true
left join lateral (
  select jsonb_agg(jsonb_build_object(
    'relation_type',x.relation_type,'relation_subtype',x.relation_subtype,
    'sense_id',x.target_sense_id,'sense_key',x.target_sense_key,
    'meaning_text',x.target_meaning,'display_pronunciation',x.target_family_label
  ) order by x.display_order,x.target_sense_id) relations
  from (
    select sr.relation_type,sr.relation_subtype,sr.display_order,
           ts.id target_sense_id,ts.sense_key target_sense_key,ts.meaning_text target_meaning,
           tf.working_label target_family_label
    from public.sense_relation sr
    join public.sense ts on ts.id=sr.to_sense_id and ts.status='ACTIVE'
    join public.expression_family tf on tf.id=ts.expression_family_id and tf.status='ACTIVE'
    where sr.from_sense_id=l.sense_id and sr.status='ACTIVE'
    union all
    select sr.relation_type,sr.relation_subtype,sr.display_order,
           ts.id,ts.sense_key,ts.meaning_text,tf.working_label
    from public.sense_relation sr
    join public.sense ts on ts.id=sr.from_sense_id and ts.status='ACTIVE'
    join public.expression_family tf on tf.id=ts.expression_family_id and tf.status='ACTIVE'
    where sr.to_sense_id=l.sense_id and sr.status='ACTIVE' and sr.is_bidirectional
  ) x
) rel on true
order by l.priority desc,l.family_id,l.sense_order;
$function$;

revoke all on function public.search_expression_sense_hub(text,integer) from public;
grant execute on function public.search_expression_sense_hub(text,integer) to anon,authenticated;

do $$
begin
  if (select count(*) from public.expression_family where family_key in ('F_YASUI_LEXICAL','F_YASUI_SUFFIX','F_TAYASUI','F_TAKAI_LEXICAL') and status='ACTIVE') <> 4 then
    raise exception 'yasui/takai pilot family count mismatch';
  end if;
  if (select count(*) from public.sense where sense_key in ('S_YASUI_PRICE','S_YASUI_EASY','S_YASUI_SUFFIX_EASY','S_TAYASUI_EASY','S_TAKAI_PRICE','S_TAKAI_HEIGHT','S_TAKAI_DEGREE') and status='ACTIVE') <> 7 then
    raise exception 'yasui/takai pilot sense count mismatch';
  end if;
  if (select count(*) from _pilot_raw_resolved) <> 3 then
    raise exception 'takai height raw example count mismatch';
  end if;
  if exists (select 1 from public.expression_relation where id in (1037,1038,1044)) then
    raise exception 'cross-sense FORM relations still exist';
  end if;
end $$;
